# Generated by Django 2.2.3 on 2020-08-09 18:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Estúdio')),
            ],
        ),
        migrations.CreateModel(
            name='Tattos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tatto', models.CharField(max_length=40, verbose_name='Nome da Tatto')),
                ('orcamento', models.IntegerField(blank=True, verbose_name='Orçamento')),
                ('tatto', models.ImageField(upload_to='fotos/%Y/%m/%d', verbose_name='Imagem da Tatto')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('mostrar', models.BooleanField(default=True, verbose_name='Mostrar')),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tattos.Estudio', verbose_name='Estúdio')),
            ],
        ),
    ]
